version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
      - "https://ipsc-backend.onrender.com/"
      - https://ipsc-backend.onrender.com/calculate-subnet
    environment:
      - PYTHONUNBUFFERED=1
      
    volumes:
      - ./backend/app:/app/app
    networks:
      - subnet-calc-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - subnet-calc-network

networks:
  subnet-calc-network:
    driver: bridge